public class ScheduleAppointment_wrapper
{
    public String FirstName {get;set;}
    public String LastName {get;set;}
    public String StreetAddress {get;set;}
    public String Suburb {get;set;}
    public String State {get;set;}
    public String PostalCode {get;set;}
    public String HomePhone {get;set;}
    public String MobilePhone {get;set;}
    public String Email {get;set;}
    public String PromoCode {get;set;}
    public String SecurityDoors {get;set;}
    public String SecurityScreens{get;set;}
    public String SteelDoorWindows{get;set;}
    public String FlyscreenRetractable {get;set;}
    public String FlyscreenWindoworDoor {get;set;}
    public String DiamondGrille {get;set;}
    public String ImportantNotes {get;set;}
    public Boolean confirm {get;set;}
    public String dateandtime {get;set;}
}