public class SlotWrapper{
    public String SlotDatefull {get;set;}
    public Date SlotDate {get;set;}
    public DateTime SlotDatetime {get;set;}
    public DateTime endSlotDatetime {get;set;}
    public String Starttime {get;set;}
    public String Endtime {get;set;}
    public DateTime Startdatetime {get;set;}
    public DateTime Enddatetime {get;set;}
    public String Datetoshow {get;set;}
    public String Slotid {get;set;}
}