@isTest
public class SlotWrapperTest {
	public static testmethod void method1(){
        SlotWrapper sw = new SlotWrapper();
        sw.Datetoshow = 'test';
        sw.SlotDatefull = 'test';
        sw.Enddatetime = System.now();
        sw.Startdatetime = system.now();
        sw.Slotid = 'asdsrewewf';
        sw.SlotDate = System.today();
        sw.SlotDatetime = system.now();
        sw.endSlotDatetime = system.now();
        sw.Starttime = 'test';
        sw.Endtime = 'test';
    }
}